"""Generate frontend/lib/data.ts from data/clustered_tracks.csv so the
dashboard renders real clustering results instead of mock data.
"""
import json
import os
from collections import Counter

import pandas as pd

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")
CLUSTERED_PATH = os.path.join(DATA_DIR, "clustered_tracks.csv")
OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "frontend", "lib", "data.ts")

FEATURE_COLS = ["energy", "danceability", "acousticness", "valence", "speechiness", "instrumentalness"]

# Cluster identity (name/color/description) is a manual interpretation of the
# k=4 run's centroid stats — keep in sync with README.md's "Cluster
# interpretations" section if cluster.py is rerun with different results.
CLUSTER_META = {
    0: {"name": "Mellow Acoustic", "color": "#4ADE80",
        "description": "Reflective singer-songwriter — country and folk leaning, highest acousticness of any cluster"},
    1: {"name": "Upbeat Pop", "color": "#F97316",
        "description": "Radio-friendly, high-energy anthems — almost entirely major key, the catch-all mainstream cluster"},
    2: {"name": "Party / EDM", "color": "#A855F7",
        "description": "Dance-floor bangers and hip-hop-adjacent hits — highest danceability and valence, mostly minor key"},
    3: {"name": "Moody Electronic", "color": "#38BDF8",
        "description": "Dark, textured house and electronic — standout instrumentalness and liveness, slower tempo"},
}


def first_artist(artist_field):
    return str(artist_field).split(",")[0].strip()


def main():
    if not os.path.exists(CLUSTERED_PATH):
        raise SystemExit(f"Missing {CLUSTERED_PATH}. Run cluster.py first.")

    df = pd.read_csv(CLUSTERED_PATH)

    clusters = []
    for cluster_id in sorted(df["cluster"].unique()):
        cluster_df = df[df["cluster"] == cluster_id]
        meta = CLUSTER_META.get(int(cluster_id), {
            "name": f"Cluster {cluster_id}", "color": "#888888", "description": "",
        })
        top_artists = [a for a, _ in Counter(cluster_df["artist_name"].map(first_artist)).most_common(3)]

        clusters.append({
            "id": int(cluster_id),
            "name": meta["name"],
            "color": meta["color"],
            "count": int(len(cluster_df)),
            **{col: round(float(cluster_df[col].mean()), 3) for col in FEATURE_COLS},
            "artists": top_artists,
            "description": meta["description"],
        })

    tracks = []
    for _, row in df.iterrows():
        tracks.append({
            "id": row["track_id"],
            "title": row["track_name"],
            "artist": row["artist_name"],
            "clusterId": int(row["cluster"]),
            "x": round(float(row["pca_1"]), 4),
            "y": round(float(row["pca_2"]), 4),
            **{col: round(float(row[col]), 4) for col in FEATURE_COLS},
        })

    ts_content = f"""// Generated by src/export_frontend_data.py from data/clustered_tracks.csv — do not edit by hand.
export interface Cluster {{
  id: number;
  name: string;
  color: string;
  count: number;
  energy: number;
  danceability: number;
  acousticness: number;
  valence: number;
  speechiness: number;
  instrumentalness: number;
  artists: string[];
  description: string;
}}

export interface Track {{
  id: string;
  title: string;
  artist: string;
  clusterId: number;
  x: number;
  y: number;
  energy: number;
  danceability: number;
  acousticness: number;
  valence: number;
  speechiness: number;
  instrumentalness: number;
}}

export const CLUSTERS: Cluster[] = {json.dumps(clusters, indent=2)};

export const TRACKS: Track[] = {json.dumps(tracks, indent=2)};
"""

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        f.write(ts_content)

    print(f"Wrote {len(clusters)} clusters and {len(tracks)} tracks to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
